create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  phone text not null,
  address text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  category text not null default 'Menu',
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles(id) on delete restrict,
  customer_name text not null,
  phone text not null,
  address text not null,
  location text not null,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')),
  total numeric(10, 2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, phone, address)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'address', '')
  )
  on conflict (id) do update set
    name = excluded.name,
    phone = excluded.phone,
    address = excluded.address,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Profiles are viewable by owner" on public.profiles;
create policy "Profiles are viewable by owner" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "Profiles are editable by owner" on public.profiles;
create policy "Profiles are editable by owner" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Available menu is public" on public.menu_items;
create policy "Available menu is public" on public.menu_items
for select using (is_available = true or exists (
  select 1 from public.profiles where id = auth.uid() and role = 'admin'
));

drop policy if exists "Customers can create own orders" on public.orders;
create policy "Customers can create own orders" on public.orders
for insert with check (auth.uid() = customer_id);

drop policy if exists "Customers can view own orders" on public.orders;
create policy "Customers can view own orders" on public.orders
for select using (auth.uid() = customer_id or exists (
  select 1 from public.profiles where id = auth.uid() and role = 'admin'
));

drop policy if exists "Customers can create order items" on public.order_items;
create policy "Customers can create order items" on public.order_items
for insert with check (exists (
  select 1 from public.orders where id = order_id and customer_id = auth.uid()
));

drop policy if exists "Customers can view own order items" on public.order_items;
create policy "Customers can view own order items" on public.order_items
for select using (exists (
  select 1 from public.orders where id = order_id and (customer_id = auth.uid() or exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  ))
));
